---

- hosts: laptop
  connection: local
  roles:
    - screen
    - firewall
    - virtual_host
    - irc
    - dropbox
    - chrome
    - docker
    - access
    - vpn
    - packer
    - httpd
    
