---

- name: Add host file entry for ipa-server
  lineinfile:
    path: /etc/hosts
    line: "{{ ipa_ip }} {{ ipa_hostname }}.{{ ipa_domain }} {{ ipa_hostname }}"

- name: Install ipa-server rpms
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ipa-server
    - freeipa-server-dns

- name: Run ipa-server-install
  shell: ipa-server-install -a {{ ipa_password }} -p {{ ipa_password }} -r {{ ipa_domain | upper }} --setup-dns --mkhomedir --no-ntp --hostname={{ ipa_hostname }}.{{ ipa_domain }} --ip-address={{ ipa_ip }} --domain={{ ipa_domain }} --no-host-dns --allow-zone-overlap -U --no-forwarders
  tags: ipa
