---

- name: Install Dropbox rpm
  yum:
    name: https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2015.10.28-1.fedora.x86_64.rpm
    state: installed

- name: Remove Dropbox repo file
  file:
    path: /etc/yum.repos.d/dropbox.repo
    state: absent
 
